extends RefCounted
class_name BattleTutorialCatalog

const TUTORIALS: Array[Dictionary] = [
	{
		"id": "battle_basics",
		"title_key": "tutorial.basics.title",
		"title_fallback": "Battle Basics",
		"description_key": "tutorial.basics.description",
		"description_fallback": "Learn card commitment, the timeline, shield, delay and fatigue.",
		"topics_key": "tutorial.basics.topics",
		"topics_fallback": "Cards / Timeline / Shield / Delay / Fatigue",
		"duration_key": "tutorial.basics.duration",
		"duration_fallback": "About 4 minutes",
		"difficulty_key": "tutorial.difficulty.intro",
		"difficulty_fallback": "Intro",
		"cards": ["quick_slash", "guard", "delay_step"],
		"enemy_id": "scout",
		"enemy_ai": false,
	},
	{
		"id": "slots_recast",
		"title_key": "tutorial.slots.title",
		"title_fallback": "Slots and Recast",
		"description_key": "tutorial.slots.description",
		"description_fallback": "Fill all three active slots, wait for one to open, and watch a used card recover.",
		"topics_key": "tutorial.slots.topics",
		"topics_fallback": "Slot cost / Slot overflow / Recast",
		"duration_key": "tutorial.slots.duration",
		"duration_fallback": "About 3 minutes",
		"difficulty_key": "tutorial.difficulty.basic",
		"difficulty_fallback": "Basic",
		"cards": ["heavy_swing", "guard", "quick_slash"],
		"enemy_id": "scout",
		"enemy_ai": false,
	},
	{
		"id": "interrupts",
		"title_key": "tutorial.interrupt.title",
		"title_fallback": "Interrupts",
		"description_key": "tutorial.interrupt.description",
		"description_fallback": "Read an interruptible enemy cast and cancel it before activation.",
		"topics_key": "tutorial.interrupt.topics",
		"topics_fallback": "Interruptible cards / Timing / Cancel",
		"duration_key": "tutorial.interrupt.duration",
		"duration_fallback": "About 2 minutes",
		"difficulty_key": "tutorial.difficulty.basic",
		"difficulty_fallback": "Basic",
		"cards": ["interrupt_shot"],
		"enemy_id": "brute",
		"enemy_ai": false,
	},
	{
		"id": "statuses",
		"title_key": "tutorial.status.title",
		"title_fallback": "Statuses and Cleanse",
		"description_key": "tutorial.status.description",
		"description_fallback": "Inspect status duration, observe bleed damage, and remove negative statuses.",
		"topics_key": "tutorial.status.topics",
		"topics_fallback": "Bleed / Weak / Duration / Cleanse",
		"duration_key": "tutorial.status.duration",
		"duration_fallback": "About 3 minutes",
		"difficulty_key": "tutorial.difficulty.basic",
		"difficulty_fallback": "Basic",
		"cards": ["field_medic", "quick_slash"],
		"enemy_id": "scout",
		"enemy_ai": false,
	},
	{
		"id": "shield_resource",
		"title_key": "tutorial.shield_resource.title",
		"title_fallback": "Shield as a Resource",
		"description_key": "tutorial.shield_resource.description",
		"description_fallback": "Build shield, then spend it to power a shield-cost attack.",
		"topics_key": "tutorial.shield_resource.topics",
		"topics_fallback": "Shield gain / Required shield / Shield cost",
		"duration_key": "tutorial.shield_resource.duration",
		"duration_fallback": "About 3 minutes",
		"difficulty_key": "tutorial.difficulty.basic",
		"difficulty_fallback": "Basic",
		"cards": ["guard", "aegis_ram"],
		"enemy_id": "guardian",
		"enemy_ai": false,
	},
	{
		"id": "timeline_control",
		"title_key": "tutorial.timeline_control.title",
		"title_fallback": "Advanced Timeline Control",
		"description_key": "tutorial.timeline_control.description",
		"description_fallback": "Stop and reverse enemy casts, then accelerate your own long cast.",
		"topics_key": "tutorial.timeline_control.topics",
		"topics_fallback": "Stop / Reverse / Haste",
		"duration_key": "tutorial.timeline_control.duration",
		"duration_fallback": "About 4 minutes",
		"difficulty_key": "tutorial.difficulty.advanced",
		"difficulty_fallback": "Advanced",
		"cards": ["chronostasis", "entropy_reversal", "heavy_swing", "haste_focus"],
		"enemy_id": "brute",
		"enemy_ai": false,
	},
	{
		"id": "recast_combo",
		"title_key": "tutorial.recast_combo.title",
		"title_fallback": "Recast Combos",
		"description_key": "tutorial.recast_combo.description",
		"description_fallback": "Use Reload to shorten a spent attack card's recast and play it again.",
		"topics_key": "tutorial.recast_combo.topics",
		"topics_fallback": "Cooldown / Reload / Reuse",
		"duration_key": "tutorial.recast_combo.duration",
		"duration_fallback": "About 3 minutes",
		"difficulty_key": "tutorial.difficulty.advanced",
		"difficulty_fallback": "Advanced",
		"cards": ["quick_slash", "reload"],
		"enemy_id": "scout",
		"enemy_ai": false,
	},
	{
		"id": "battle_growth",
		"title_key": "tutorial.growth.title",
		"title_fallback": "In-battle Card Growth",
		"description_key": "tutorial.growth.description",
		"description_fallback": "Trigger permanent battle modifiers and compare the live green values.",
		"topics_key": "tutorial.growth.topics",
		"topics_fallback": "Temporary modifiers / Live tooltip / Scaling",
		"duration_key": "tutorial.growth.duration",
		"duration_fallback": "About 3 minutes",
		"difficulty_key": "tutorial.difficulty.advanced",
		"difficulty_fallback": "Advanced",
		"cards": ["self_tuning_edge", "self_tuning_edge"],
		"enemy_id": "scout",
		"enemy_ai": false,
	},
	{
		"id": "auto_queue",
		"title_key": "tutorial.auto_queue.title",
		"title_fallback": "Automatic Queues",
		"description_key": "tutorial.auto_queue.description",
		"description_fallback": "Create cards automatically and observe self-repeating timeline entries.",
		"topics_key": "tutorial.auto_queue.topics",
		"topics_fallback": "Generated cards / Auto queue / Recursive cards",
		"duration_key": "tutorial.auto_queue.duration",
		"duration_fallback": "About 3 minutes",
		"difficulty_key": "tutorial.difficulty.advanced",
		"difficulty_fallback": "Advanced",
		"cards": ["sequence_loader", "auto_turret", "quick_slash"],
		"enemy_id": "scout",
		"enemy_ai": false,
	},
	{
		"id": "combat_exam",
		"title_key": "tutorial.exam.title",
		"title_fallback": "Combat Exercise",
		"description_key": "tutorial.exam.description",
		"description_fallback": "Win a guided-free battle using slots, shield, delay, cleanse and interrupts.",
		"topics_key": "tutorial.exam.topics",
		"topics_fallback": "Full battle / No step prompts / Victory",
		"duration_key": "tutorial.exam.duration",
		"duration_fallback": "About 5 minutes",
		"difficulty_key": "tutorial.difficulty.practice",
		"difficulty_fallback": "Practice",
		"cards": ["quick_slash", "guard", "interrupt_shot", "delay_step", "field_medic"],
		"enemy_id": "brute",
		"enemy_ai": true,
	},
]


static func get_all() -> Array[Dictionary]:
	return TUTORIALS.duplicate(true)


static func get_tutorial(tutorial_id: String) -> Dictionary:
	for tutorial: Dictionary in TUTORIALS:
		if String(tutorial.get("id", "")) == tutorial_id:
			return tutorial.duplicate(true)
	return {}


static func has_tutorial(tutorial_id: String) -> bool:
	return not get_tutorial(tutorial_id).is_empty()
